name: GPT Pull Request Updater

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout GPT-PullRequest-Updater
        uses: actions/checkout@v2
        with:
          repository: ravilushqa/gpt-pullrequest-updater
          path: gpt-pullrequest-updater

      - name: Build description and review commands
        run: |
          cd gpt-pullrequest-updater
          go build -o description ./cmd/description
          go build -o review ./cmd/review

      - name: Update Pull Request Description
        run: |
          ./gpt-pullrequest-updater/description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.number }}

      - name: Review Pull Request
        if: github.event.action == 'opened'
        run: |
          ./gpt-pullrequest-updater/review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.number }}
